export { default as HeroSection } from "./HeroSection";
export { default as FamilyOverviewSection } from "./FamilyOverviewSection";
export { default as CatalogueSection } from "./CatalogueSection";
export { default as DetailStructureSection } from "./DetailStructureSection";
export { default as EvidenceRelationshipsSection } from "./EvidenceRelationshipsSection";
export { default as TelecomTaxRelevanceSection } from "./TelecomTaxRelevanceSection";
export { default as InteroperabilitySection } from "./InteroperabilitySection";
export { default as AssuranceBoundariesSection } from "./AssuranceBoundariesSection";
export { default as EvidenceCurrentnessSection } from "./EvidenceCurrentnessSection";
export { default as ReviewMethodologySection } from "./ReviewMethodologySection";
export { default as BuyerPathwaysSection } from "./BuyerPathwaysSection";
export { default as FAQSection } from "./FAQSection";
export { default as ClosingCTASection } from "./ClosingCTASection";
export * from "./shared";
export * from "./industry-standards-data";
