export * from "./types";
export * from "./shared";
export { default as HeroSection } from "./HeroSection";
export { default as RelationshipTypesSection } from "./RelationshipTypesSection";
export { default as RegistryDiscoverySection } from "./RegistryDiscoverySection";
export { default as PartnerRecordAnatomySection } from "./PartnerRecordAnatomySection";
export { default as TechnologyScopeSection } from "./TechnologyScopeSection";
export { default as AccountabilityModelSection } from "./AccountabilityModelSection";
export { default as RelationshipLifecycleSection } from "./RelationshipLifecycleSection";
export { default as InquiryBoundarySection } from "./InquiryBoundarySection";
export { default as DirectAnswersSection } from "./DirectAnswersSection";
export { default as VerificationNextStepsSection } from "./VerificationNextStepsSection";
export { ResourcesPartnersContent, default } from "./ResourcesPartnersContent";
